[build]
  base = "apps/docs"
  command = "npm install && npm run build"
  publish = "dist"

[[redirects]]
  from = "/tcode"
  to = "/tcode.html"
  status = 200

[[redirects]]
  from = "/tcode/"
  to = "/tcode.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
